# Generated by Django 5.2 on 2025-10-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_collectibleitem_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
