# Generated by Django 5.2 on 2025-10-20 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_collectibleitem_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 14, 36, 11, 78232)),
        ),
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
