# Generated by Django 5.2 on 2025-10-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.PositiveIntegerField(),
        ),
    ]
