# Generated by Django 5.2 on 2025-12-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
    ]
