# Generated by Django 5.2 on 2025-12-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_position_distance_position_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
