# Generated by Django 5.2 on 2025-10-20 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_alter_position_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 9, 26, 38, 941841)),
        ),
    ]
