# Generated by Django 5.2 on 2026-01-11 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_alter_position_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 11, 8, 34, 49, 455301, tzinfo=datetime.timezone.utc)),
        ),
    ]
